<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260826122738 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9D17F50A6 ON app_user (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE appointment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, subject TEXT DEFAULT NULL, special_page_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE38F844D17F50A6 ON appointment (uuid)');
        $this->addSql('CREATE INDEX IDX_FE38F844D44A3F71 ON appointment (special_page_id)');
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, show_in_menu BOOLEAN DEFAULT false NOT NULL, menu_order INT DEFAULT 0 NOT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23A0E66D17F50A6 ON article (uuid)');
        $this->addSql('CREATE INDEX IDX_23A0E6612469DE2 ON article (category_id)');
        $this->addSql('CREATE TABLE association (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, address VARCHAR(255) DEFAULT NULL, phone_number VARCHAR(20) DEFAULT NULL, linkedin_link VARCHAR(255) DEFAULT NULL, instagram_link VARCHAR(255) DEFAULT NULL, contact_email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FD8521CCD17F50A6 ON association (uuid)');
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, menu_order INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1D17F50A6 ON category (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)');
        $this->addSql('CREATE TABLE linked_in_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, embed_link VARCHAR(500) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1B796B7ED17F50A6 ON linked_in_post (uuid)');
        $this->addSql('CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, name VARCHAR(255) NOT NULL, logo VARCHAR(255) DEFAULT NULL, website_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A2CA10CD17F50A6 ON media (uuid)');
        $this->addSql('CREATE TABLE partner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, title VARCHAR(255) DEFAULT NULL, subtitle VARCHAR(255) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, website_url VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, position INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_312B3E16D17F50A6 ON partner (uuid)');
        $this->addSql('CREATE TABLE press_mention (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, title VARCHAR(255) DEFAULT NULL, type VARCHAR(50) DEFAULT \'Article\' NOT NULL, external_link VARCHAR(500) DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, media_id INT DEFAULT NULL, special_page_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B4AB945D17F50A6 ON press_mention (uuid)');
        $this->addSql('CREATE INDEX IDX_7B4AB945EA9FDD75 ON press_mention (media_id)');
        $this->addSql('CREATE INDEX IDX_7B4AB945D44A3F71 ON press_mention (special_page_id)');
        $this->addSql('CREATE TABLE special_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, identifier VARCHAR(50) NOT NULL, content TEXT DEFAULT NULL, show_in_menu BOOLEAN DEFAULT false NOT NULL, menu_order INT DEFAULT 0 NOT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_965DB70BD17F50A6 ON special_page (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_965DB70B989D9B62 ON special_page (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_965DB70B772E836A ON special_page (identifier)');
        $this->addSql('CREATE INDEX IDX_965DB70B12469DE2 ON special_page (category_id)');
        $this->addSql('CREATE TABLE team_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, role VARCHAR(255) DEFAULT NULL, bio TEXT DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, photo_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6FFBDA1D17F50A6 ON team_member (uuid)');
        $this->addSql('CREATE INDEX IDX_6FFBDA17E9E4C8C ON team_member (photo_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844D44A3F71 FOREIGN KEY (special_page_id) REFERENCES special_page (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E6612469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE press_mention ADD CONSTRAINT FK_7B4AB945EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE press_mention ADD CONSTRAINT FK_7B4AB945D44A3F71 FOREIGN KEY (special_page_id) REFERENCES special_page (id)');
        $this->addSql('ALTER TABLE special_page ADD CONSTRAINT FK_965DB70B12469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE team_member ADD CONSTRAINT FK_6FFBDA17E9E4C8C FOREIGN KEY (photo_id) REFERENCES media (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844D44A3F71');
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E6612469DE2');
        $this->addSql('ALTER TABLE press_mention DROP CONSTRAINT FK_7B4AB945EA9FDD75');
        $this->addSql('ALTER TABLE press_mention DROP CONSTRAINT FK_7B4AB945D44A3F71');
        $this->addSql('ALTER TABLE special_page DROP CONSTRAINT FK_965DB70B12469DE2');
        $this->addSql('ALTER TABLE team_member DROP CONSTRAINT FK_6FFBDA17E9E4C8C');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE appointment');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE association');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE linked_in_post');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE partner');
        $this->addSql('DROP TABLE press_mention');
        $this->addSql('DROP TABLE special_page');
        $this->addSql('DROP TABLE team_member');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
